
[Interface]
Address = 10.101.0.12/32
PrivateKey = eDWn51SFCKN6hJQ5gKKwSwspSGQstWHjMqVLsTbFi0I=
PostUp = printf 'You can now access http://0.0.0.0:3000 on https://xgake2.tunnel.pyjam.as/ ✨\n'

[Peer]
PublicKey = 9svuW2NY2wAOZi12FOq4KX7GYfZbpJI+qg/g1dIuDi4=
AllowedIPs = 10.101.0.1/32
Endpoint = tunnel.pyjam.as:55555
PersistentKeepalive = 21
